repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.0
  hooks:
  - id: ruff-format
    description: "Ruff formatting"
  - id: ruff-check
    description: "Ruff linting"
    args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/northisup/pyright-pretty
  rev: v0.1.0
  hooks:
  - id: pyright-pretty
