repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: pnpm lint
        language: system
        pass_filenames: false
        files: \.(ts|tsx|js)$
      - id: tsc
        name: tsc
        entry: pnpm typecheck
        language: system
        pass_filenames: false
        files: \.(ts|tsx)$
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --manifest-path src-tauri/Cargo.toml --check
        language: system
        pass_filenames: false
        files: \.rs$
